# Generated by Django 4.2.3 on 2023-08-03 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "createdAt",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="Город"),
                ),
                (
                    "address",
                    models.CharField(blank=True, max_length=250, verbose_name="Адрес"),
                ),
                (
                    "totalCost",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Итоговая цена"
                    ),
                ),
                (
                    "deliveryType",
                    models.CharField(
                        choices=[("free", "Free"), ("paid", "Paid")],
                        max_length=15,
                        verbose_name="Тип доставки",
                    ),
                ),
                (
                    "paymentType",
                    models.CharField(
                        choices=[("online", "Online"), ("offline", "Offline")],
                        max_length=15,
                        verbose_name="Тип оплаты",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("accepted", "Accepted"),
                            ("processing", "Processing"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        max_length=15,
                        verbose_name="Статус заказа",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
            },
        ),
    ]
