version: "3.9"

services:
  app:
    build:
      dockerfile: ./Dockerfile
    command:
      - "python"
      - "manage.py"
      - "runserver"
      - "0.0.0.0:8000"
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"
    volumes:
      - ./megano/database:/app/database