# Generated by Django 4.2.3 on 2023-07-27 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products_app", "0003_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product",
                to="products_app.category",
                verbose_name="Категория",
            ),
        ),
    ]
