# Generated by Django 4.2.3 on 2023-07-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products_app", "0004_alter_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="dateFrom",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата начала"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="dateTo",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата окончания"
            ),
        ),
    ]
