# Generated by Django 4.2.3 on 2023-08-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products_app", "0007_category_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="src",
            field=models.ImageField(
                default="product_images/default.png",
                upload_to="product_images",
                verbose_name="Ссылка",
            ),
        ),
    ]
