# Generated by Django 4.2.3 on 2023-08-05 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products_app", "0008_alter_productimage_src"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="alt",
            field=models.CharField(
                default="Image alt string", max_length=128, verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="products_app.product",
                verbose_name="Продукт",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="src",
            field=models.ImageField(upload_to="product_images", verbose_name="Ссылка"),
        ),
    ]
