# Generated by Django 4.2.3 on 2023-08-05 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "products_app",
            "0009_alter_productimage_alt_alter_productimage_product_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="author",
        ),
        migrations.RemoveField(
            model_name="review",
            name="email",
        ),
        migrations.AddField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="review",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="products_app.product",
                verbose_name="Продукт",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="rate",
            field=models.IntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")]
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="text",
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
