# Generated by Django 4.2.3 on 2023-07-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(default='auth_app/avatars/default.png', upload_to='auth_app/avatars/user_avatars', verbose_name='Ссылка')),
                ('alt', models.CharField(max_length=128, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Аватар',
                'verbose_name_plural': 'Аватары',
            },
        ),
    ]
