# Generated by Django 4.2.3 on 2023-07-21 14:33

from django.db import migrations, models
import auth_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.png', null=True, upload_to=auth_app.models.avatar_upload_path, verbose_name='Аватар'),
        ),
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
