# Generated by Django 4.2.3 on 2023-07-21 14:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auth_app", "0003_profile_email_alter_profile_avatar_delete_avatar"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name": "Профиль", "verbose_name_plural": "Профили"},
        ),
    ]
